# Configuración de puerto
quarkus.http.port=8080

# SOAP Endpoint configuration para CXF
quarkus.cxf.endpoint."/batches".implementor=enfok.server.endpoint.BatchEndpoint
quarkus.cxf.endpoint."/batches".in-interceptors=enfok.server.config.TokenValidationInterceptor

quarkus.cxf.endpoint."/auth".implementor=enfok.server.endpoint.AuthEndpoint

quarkus.cxf.endpoint."/user".implementor=enfok.server.endpoint.UserEndpoint
quarkus.cxf.endpoint."/user".in-interceptors=enfok.server.config.TokenValidationInterceptor

quarkus.cxf.endpoint."/bd".implementor=enfok.server.endpoint.BdEndpoint
quarkus.cxf.endpoint."/bd".in-interceptors=enfok.server.config.TokenValidationInterceptor

quarkus.cxf.endpoint."/node".implementor=enfok.server.endpoint.NodeEndpoint
quarkus.cxf.endpoint."/node".in-interceptors=enfok.server.config.TokenValidationInterceptor


quarkus.grpc.server.port=9000
# Ubicación custom de archivos .proto (por defecto sería src/main/proto)
quarkus.generate-code.grpc.scan-for-proto=enfok/server/proto


# Para que veas fácilmente logs de Quarkus y CXF
quarkus.log.level=INFO


