# Configuración de puerto
quarkus.http.port=8080

# SOAP Endpoint configuration para CXF
quarkus.cxf.endpoint."/batches".implementor=enfok.server.endpoint.BatchEndpoint
quarkus.cxf.endpoint."/batches".in-interceptors=enfok.server.config.TokenValidationInterceptor

# Para que veas fácilmente logs de Quarkus y CXF
quarkus.log.level=INFO
